### ISSUE TITLE
Quiz Yourself (Hint Feature for Each Word)

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#122]
# Background
It will be great if you can create your own quiz and store it with the wordcard.
This way I personally do not have to store the hints with a separate Google Docs.

## TODOs
```
- [ ] Implement a Quiz/Non Quiz Mode?
- [ ] Check if the `tags` should be still visible
- [ ] Check if the `Dictionaries` should be still visible => probably not
- [ ] Implement API
```

**Comment by mlajkim** [comment]
This issue is closed as the following TODOs for this issue has been handled

- [x] Implement a Quiz/Non Quiz Mode?
  - handled in https://github.com/ajktown/wordnote/pull/142
- [X] Check if the `tags` should be still visible
  - Tags are visible with the PR https://github.com/ajktown/wordnote/pull/142
- [X] Check if the `Dictionaries` should be still visible => probably not
  - Dictionaries are visible as it is inconvenient not to
  - Handled in https://github.com/ajktown/wordnote/pull/170
- [X] Implement API
  - Actually, the implementation for API was not required to make this enhancement done
