### ISSUE TITLE
Refresh Button Minor Bug When No Word Found for User

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#123]
# Background
When a user without any words (or AKA no semesters so far) won't have his/her preference updated when the refresh button is clicked (or automatically clicked once you open Wordnote on browser).

This is due to the fact that the refresh flow ends when the latestSemester is undefined (when the user never has created a single word yet) as the red square in following activity diagram:
![image](https://github.com/ajktown/wordnote/assets/53258958/ff38db02-d675-40dc-a2fb-7fd3e4501636)

## TODOs
- [ ] Fix the diagram
- [ ] Fix the flow (so that the `getPreference()` is always run
- [ ] Make sure that the `getSemesters()` and `getPreference()` run simultaneously
- [ ] Write more TODOs
