### ISSUE TITLE
First Time User with Confetti

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#128]
# Background
I personally felt great when I found the confetti for the first discussion in Github
![image](https://github.com/ajktown/wordnote/assets/53258958/9dca6c6a-794f-4760-8a21-5ab50f73d75a)

## TODOs
```
- [ ] Find the appropriate pacakge for confetti (Check if it works)
- [ ] Change API so that it returns if end user is signed in for the first time.
- [ ] Implement confetti for the first time user
- [ ] Write Congratulation message too, just like GitHub
```
