### ISSUE TITLE
useGoogleOneTabSignIn & useGoogleSignInHandlers Refactor

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#137]
# Background
`useDevSignIn()` hook will be (has been) fixed in the PR https://github.com/ajktown/wordnote/pull/136.

I want to get the `useGoogleOneTabSignIn()` and `useGoogleSignInHandlers()` fixed as the `useDevSignIn()`

## TODOs
```
- [ ] TODO: Write TODOs
- [ ] Fix useGoogleOneTapLogin's `Promise-returning function provided to property where a void return was expected.` warning
- [ ] Fix `Promise-returning function provided to variable where a void return was expected.` warning
- [ ] Try to remove these types if possible
```ts
type PrivateOnSuccess = (credentialResponse: CredentialResponse) => void
type PrivateOnError = () => void
type UseGoogleSignInHandlers = [PrivateOnSuccess, PrivateOnError]
```ts
```
