### ISSUE TITLE
Favorite Icon Improvement for WordCard

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#160]
### Background

Clicking favorite icon requires API response. I want the click to be instantaneous, and roll back if the modification fails.
![image](https://github.com/ajktown/wordnote/assets/53258958/ff4abe43-621d-41d0-800d-9fe8e1b91fe1)

### TODOs

```
- [ ] Update the icon as soon as the end user clicks
- [ ] If API Request fails, roll back and write a simple snackbar that shows "failed to favorite (unfavorite) the word"
- [ ] If API Request successes, apply the given latest favorite status
```
