### ISSUE TITLE
Search word in WordCard opens a SearchResult Dialog

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#193]
### Background

Search button provided within the WordCard should open a dialog with the search result based on the WordCard.
This way current looking view does not get modified.

![image](https://github.com/ajktown/wordnote/assets/53258958/f580fb49-f7c3-40d4-8295-db4d56caa820)

### TODOs

```
- [ ] Implement Dialog style search results, that do not modify current looking ones
- [ ] Also the search should be modifiable within the dialog
- [ ] Search must be done during the review mode too
```
