### ISSUE TITLE
Implement favorite only semester icon that brings every word of Wordnote

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#206]
### Background

Implement favorite only semester icon that brings every word of Wordnote

### TODOs

```
- [ ] Implement favorite only semester icon that brings every word of Wordnote
- [ ] User can use a preference setting of automatic review mode if favorite semester is clicked 
- [ ] User can use a preference setting of automatic non-review mode if non-favorite semester is clicked
```

**Comment by mlajkim** [comment]
Closed as implemented in https://github.com/ajktown/wordnote/pull/208
