### ISSUE TITLE
Feat: Tags with Custom Colors

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#232]
### Background

Color is a great distinguisher as human eyes catch colors much faster than actual words.
It will be great for users to custom their colors under preference.

For example, if user has the following setting, their tag named "must-remember" will be colored as they define:
```ts
{
  customTagColors: {
    "must-remember": "#FF0000" // red
  }
}
```

### TODOs

```
- [ ] Make changes in API so that it accepts custom color for tags
- [ ] Make UI read/apply the custom colors defined by the users
- [ ] Let users be able to change their tag colors on UI
```
