### ISSUE TITLE
Tags should be addable for edit

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#42]
# Background
Here is the list of features available for adding/deleting tags available at this point on Sep 14, 2023
- You can create a word with tag only for the first time you create the word
  - `word:meaning=example sentence#this-is-tag #this-is-another-tag`
- You can delete tag 
  - ![image](https://github.com/ajktown/wordnote/assets/53258958/5ac049dd-e8d2-4b58-ba4d-6511333e8035)

But you **cannot** attach a new tag after you create a word at this point.

## TODOs
- [x] API is already available for adding new tag. Make a functionality for the FE.
- [x] Design the adding tag
- [x] If new tag is added, It should add it into the current semester
- [ ] Make sure it implements hook for modifying the word
