### ISSUE TITLE
Refactor hook naming convention and its usage

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#44]
# Background
A hook should always return a function with an `on` prefix, as it is defined inside the useHook. Furthermore, when an `onHook` is returned to any component, the component can retain the `onHook` naming convention, since it's not derived from another component. The `Handle` prefix should only be applied when passing any function from one component to another.

## TODOs
```
- [ ] Wait until https://github.com/ajktown/wordnote/pull/101 is merged
- [ ] Refactor every hook to have the prefix `on` for functions they return
- [ ] Refactor every component that takes the function from hook to keep the same name
- [ ] Double check if function with prefix `handle` is incorrectly used. 
- [ ] Write an issue with [doc](https://github.com/ajktown/docs/issues) to handle the changes of the changes here later on documentation too. 
```

## Sample
```ts
import { putWordByIdApi } from '@/api/words/put-word-by-id.api'
import { WordDataModifiable } from '@/api/words/interfaces'
import { wordsFamily } from '@/recoil/words/words.state'
import { useRecoilCallback } from 'recoil'

type UsePutWord = (modified: Partial<WordDataModifiable>) => Promise<void> // onPutWord

/** Returns a function that modifies a specific attribute of WordData by making an API request. 
 * Upon successful API call, the API returns the updated version which is subsequently saved.
 */
export const usePutWord = (wordId: string): UsePutWord => {
  const onPutWord = useRecoilCallback(
    ({ snapshot, set }) =>
      async (modified: Partial<WordDataModifiable>) => {
        const wordData = await snapshot.getPromise(wordsFamily(wordId))
        if (wordData == null) return

        const [modifiedWord] = await putWordByIdApi(wordId, modified)
        set(wordsFamily(wordId), modifiedWord)
      },
    [],
  )

  return onPutWord
}
```

```ts
const onPutWord = usePutWord(wordId)
```
