### ISSUE TITLE
Secret data securely stored on secret.yaml

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#60]
## Backgrounds
At present, the `deployment.yaml` file is included in the .gitignore because the ConfigMap isn't functioning as anticipated.

I'd like to adjust this so that only secret values are ignored by git, while the rest of the settings are managed using ConfigMap.

Furthermore, I aim to restructure the environment file to align with Kubernetes ConfigMap and Secret configurations.

## TODOs
- [ ] Create a secret yaml with sensitive data and it must be included in the `.gitginore` 
- [ ] Create a configmap yaml that is read by deployment
- [ ] Remove deployment from gitignore
- [ ] Restructure `.env` with sensitive and non-sensitive data

**Comment by mlajkim** [comment]
Was handled here: https://github.com/ajktown/docs/pull/15
