### ISSUE TITLE
Word Card with Dictionary Link

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#68]
## Backgrounds
It will be great if I can have simple buttons that open a page of the word

### First Stage
It is 100% fixed 
- If English
  - Dictionary.com
  - en.dict.naver.com
  - urbandictionary.com/define.php?term=test
- If Korean
  -  ko.dict.naver.com
- If Japanese
  - ja.dict.naver.com
- If Chinese
  - zh.dict.naver.com

### Second Stage
- You can modify your own with prefix of link
  - Only support if page supports the term placed at the last of the link

### Third Stage
You can modify with regex format

## TODOs
- [ ] Develop the First Stage
- [ ] Write an issue for Second Stage
- [ ] The issue should mention this issue

**Comment by mlajkim** [comment]
Handled on https://github.com/ajktown/wordnote/pull/69
