### ISSUE TITLE
Loading for Modifying Word

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#82]
# Background
When you modify word, it should have a loading with the input not get deleted automatically.
This way if connection failed, the user's input is still stored on FE.
![image](https://github.com/ajktown/wordnote/assets/53258958/e6ec2785-493d-463a-9b4f-c4198f8bdfe9)

## TODOs
- [ ] After modify, the user's input should be still stored
- [ ] Loading UI should be available
- [ ] Some of the contents should be disabled ...?
